---
title: "May2018LightExperiment"
author: "Anamica Bedi de Silva"
date: "5/24/2018"
output: html_document
---
####Reading in and Shaping Plate Reader Data
```{r, warning=FALSE, echo=FALSE}

rm(list=ls())

library(readxl)
library(lubridate)
setwd('/Users/nankabd/Library/CloudStorage/GoogleDrive-abedi@hawaii.edu/My Drive/May2018LightExperiments')
#Raw plate reader data containing RFU for wells in each Micromonas culturing plate
folders=list.files('/Users/nankabd/Library/CloudStorage/GoogleDrive-abedi@hawaii.edu/My Drive/May2018LightExperiments', full.names=TRUE) 

#Labels containing sample information (isolate identity, light condition, transfer #, etc.) for each well of each plate
well.label.files=list.files('/Users/nankabd/Library/CloudStorage/GoogleDrive-abedi@hawaii.edu/My Drive/May2018LightExperimentInfo', full.names=TRUE)

#Merge plate reader date with sample information
for (j in 1:length(folders)) {
  
  files = list.files(folders[j])
  setwd(folders[j])
  well.labels = read.csv(well.label.files[j])
  
  for (i in 1:length(files)) {
    
    datanow = read_xlsx(files[i], range = 'B52:G55', col_names = FALSE)
    
    data.date = as_datetime(as.character(read_excel(files[i], range = 'E48', col_names = FALSE)), tz="HST")
    
    well.labels$RFU = as.vector(t(as.matrix(datanow[,])))
    well.labels$date = data.date
    
    if (i == 1) plate.timeseries = well.labels
    if (i > 1) plate.timeseries = rbind(plate.timeseries, well.labels)
    
  }
  
  if (j == 1) db.whole = plate.timeseries
  if (j > 1) db.whole = rbind(db.whole, plate.timeseries)
  
}

#Excluding data that is over the limit of plate reader detection
db<-db.whole[!(db.whole$RFU=="OVER"),]

#Classifying data columns and/or renaming columns
db$RFU<-as.numeric(db$RFU)
db$short.date<-substr(db$date, 1,10)
names(db)[12]<-"Transfer"
levels(db$Transfer)<-sub("w", "T", levels(db$Transfer))

db$plate.transfer<-paste(db$Plate, db$Transfer)
db<-db[with(db, order(date)),] 
db<-db[with(db, order(plate.transfer)),]
db$ID.plate<-as.factor(paste(db$SampleID, db$Plate))


```


###Subsetting based on light & reading in dates of exponential growth
```{r, echo=F}
##Creating high light data frame
high<-subset(db, Light=="high")

##Adding column with YYYY-MM-DD format, not YYYY-MM-DD-HH-MM-SS
days<-unique(high$short.date) 

##finding mean of blanks from each day to subtract from RFU data
for (i in 1:length(days)){
  dates<-subset(high, short.date==days[i])
  blanks<-subset(dates, SampleID=="blank")
  blanks<-subset(blanks, !(RFU>40))
  mean.b<-mean(blanks$RFU)
  high$bRFU<-(high$RFU-mean.b)
  
} 

#Excluding negative numbers
high<-subset(high, !(bRFU<=0)) 

#Reading in data with dates for exponential phase growth
hi.dates<-read.csv('hidatelist.csv') #dates of exponential growth for each curve

#Subset of reading from second transfer. If you don't change to HST then it's in universal time is used and that's a mess
hi.dates$T2.start<-mdy(hi.dates$T2.start, tz="HST") 
hi.dates$T2.end<-mdy(hi.dates$T2.end, tz="HST")
hour(hi.dates$T2.start)<-1
hour(hi.dates$T2.end)<-23

hi.dates$T3.start<-mdy(hi.dates$T3.start, tz="HST")
hi.dates$T3.end<-mdy(hi.dates$T3.end, tz="HST")
hour(hi.dates$T3.start)<-1
hour(hi.dates$T3.end)<-23

hi.dates$T4.start<-mdy(hi.dates$T4.start, tz="HST")
hi.dates$T4.end<-mdy(hi.dates$T4.end, tz="HST")
hour(hi.dates$T4.start)<-1
hour(hi.dates$T4.end)<-23


##Creating low light data frame. Uses steps as above for high light data frame.
low<-subset(db, Light=="low")

days<-unique(low$short.date)

for (i in 1:length(days)){
  dates<-subset(low, short.date==days[i])
  blanks<-subset(dates, SampleID=="blank")
  blanks<-subset(blanks, !(RFU>40))
  mean.b<-mean(blanks$RFU)
  low$bRFU<-(low$RFU-mean.b)
  
}

low<-subset(low, !(bRFU<=0))

lo.dates<-read.csv('lodatelist.csv')

lo.dates$T2.start<-mdy(lo.dates$start.T2, tz="HST")
lo.dates$T2.end<-mdy(lo.dates$end.T2, tz="HST")
hour(lo.dates$T2.start)<-1
hour(lo.dates$T2.end)<-23

lo.dates$T3.start<-mdy(lo.dates$start.T3, tz="HST")
lo.dates$T3.end<-mdy(lo.dates$end.T3, tz="HST")
hour(lo.dates$T3.start)<-1
hour(lo.dates$T3.end)<-23

```

###Subsetting based on Transfer
```{r, echo=F}
hiT2<-subset(high,Transfer=="T2")
hiT2.dates<-data.frame("ID.plate"=hi.dates$ID.plate, "start"= hi.dates$T2.start, "end"=hi.dates$T2.end)

hiT3<-subset(high,Transfer=="T3")
hiT3.dates<-data.frame("ID.plate"=hi.dates$ID.plate, "start"= hi.dates$T3.start, "end"=hi.dates$T3.end)

hiT4<-subset(high, Transfer=="T4")
hiT4.dates<-data.frame("ID.plate"=hi.dates$ID.plate, "start"= hi.dates$T4.start, "end"=hi.dates$T4.end)

hi.all.T<-subset(high, !(Transfer=="T1"))

lowT2<-subset(low,Transfer=="T2")
lowT2.dates<-data.frame("ID.plate"=lo.dates$ID.plate, "start"= lo.dates$T2.start, "end"=lo.dates$T2.end)

lowT3<-subset(low,Transfer=="T3")
lowT3.dates<-data.frame("ID.plate"=lo.dates$ID.plate, "start"= lo.dates$T3.start, "end"=lo.dates$T3.end)

```

####Defining Function for Regression and Plotting Loop

```{r, echo=F}
loops<-function(x, y){ 
par(mfrow=c(4,3), mar=c(4,3,1,0))
host<-vector()
virus<-vector()
cross<-vector()
resist<-vector()
transfer<-vector()
plate.name<-vector()
light<-vector()
reg<-vector()
isolate<-vector()
reg<-vector()
sampleid<-vector()
isolate<-vector()
spec.isolate<-vector()
max.rfu<-vector()
Names<-unique(x$ID.plate)

  for(i in 1:length(Names)){
    sub.samp<-subset(x, ID.plate==Names[i])
    sub.samp<-merge(sub.samp, y)
    if (is.na(sub.samp$start[1])) next
  
    sub.date<-subset(sub.samp, sub.samp$start <= sub.samp$date & sub.samp$date<=sub.samp$end)
    
    plot(bRFU~date, sub.date, type='b', main=Names[i], las=2, log='y')
    reg[i]<-coef(lm(log(bRFU) ~ date, sub.date))[2]
    
    host[i]<-as.character(sub.date$Host[1])
    virus[i]<-as.character(sub.date$Virus[1])
    cross[i]<-as.character(sub.date$Cross[1])
    resist[i]<-as.character(sub.date$Resistance[1])
    transfer[i]<-as.character(sub.date$Transfer[1])
    plate.name[i]<-as.character(sub.date$Plate[1])
    light[i]<-as.character(sub.date$Light[1])
    spec.isolate[i]<-as.character(sub.date$SampleID[1])
    isolate[i]<-substr(sub.date$SampleID, 1, nchar(as.character(sub.date$SampleID))-1)
    sampleid[i]<-as.character(sub.date$ID.plate[1])
    max.rfu[i]<-max(sub.date$bRFU)
}

slope<-reg*(24*3600)

all.dat<-data.frame(sampleid,spec.isolate, host, virus, cross, resist, transfer, plate.name, light, slope, isolate, max.rfu)
all.dat$virus<-as.character(all.dat$virus)
all.dat$virus[is.na(all.dat$virus)]<-"None"
return(all.dat)
}

```


###High Growth Rate Data Frames
```{r, warning=F, echo=F}

hiT2.loops<-loops(hiT2, hiT2.dates)

hiT3.loops<-loops(hiT3, hiT3.dates)

hiT4.loops<-loops(hiT4, hiT4.dates)

hi.all.loops<-rbind(hiT2.loops, hiT3.loops, hiT4.loops)

```


###Low Growth Rate Data Frames
```{r, warning=F, echo=F}
loT2.loops<-loops(lowT2, lowT2.dates)

loT3.loops<-loops(lowT3, lowT3.dates)

lo.all.loops<-rbind(loT2.loops,loT3.loops)

all.loops<-rbind(hi.all.loops, lo.all.loops)
```

###Mixed Models for FL13 and FL42, respectively
```{r}
library(lattice)
library(lme4)
library(effects)
library(lmerTest)

no.blanks<-subset(all.loops, cross!="blank")
no.blanks<-na.omit(no.blanks)
no.blanks$cross<-no.blanks$cross[,drop=T]


x.13<-c("FL13x13v", "FL13x22v", "FL13x28v")
x.42<-c("FL42x42v", "FL42x22v", "FL42x28v")
x.all<-c("FL13x13v", "FL13x22v", "FL13x28v","FL42x22v", "FL42x28v", "FL42x42v")

```

```{r}
#For FL13
##Main data frame, including high and low light
big.buddy = subset(no.blanks, cross %in% x.13)

##Main model
tmb.mod = glmmTMB(slope ~ resist*light + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.buddy)

##Submodels
tmb.noint  = glmmTMB(slope ~ resist + light + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.buddy)

anova(tmb.mod, tmb.noint)

big.hi<-subset(big.buddy, light==("high"))
tmb.hi<-glmmTMB(slope~resist + (1|plate.name) + (1|isolate),dispformula =~ resist, data=big.hi)
hi.ran<-glmmTMB(slope~ 1 + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.hi)
anova(tmb.hi, hi.ran)

big.lo<-subset(big.buddy, light==("low"))
tmb.lo<-glmmTMB(slope~resist + (1|plate.name) + (1|isolate),dispformula =~ resist, data=big.lo)
lo.ran<-glmmTMB(slope~1 + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.lo)
anova(tmb.lo, lo.ran)


##For FL42
big.buddy = subset(no.blanks, cross %in% x.42)

##Main model
tmb.mod = glmmTMB(slope ~ resist*light + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.buddy)

##Submodels
tmb.noint  = glmmTMB(slope ~ resist + light + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.buddy)

anova(tmb.mod, tmb.noint)

big.hi<-subset(big.buddy, light==("high"))
tmb.hi<-glmmTMB(slope~resist + (1|plate.name) + (1|isolate),dispformula =~ resist, data=big.hi)
hi.ran<-glmmTMB(slope~ 1 + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.hi)
anova(tmb.hi, hi.ran)

big.lo<-subset(big.buddy, light==("low"))
tmb.lo<-glmmTMB(slope~resist + (1|plate.name) + (1|isolate),dispformula =~ resist, data=big.lo)
lo.ran<-glmmTMB(slope~1 + (1|plate.name) + (1|isolate), dispformula =~ resist, data=big.lo)
anova(tmb.lo, lo.ran)
```
